application: myapp
version: alpha-001
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: static/css/

- url: /(.*\.(gif|png|jpg|svg))$
  static_files: static/\1
  upload: static/img/.*\.(gif|png|jpg|svg)$

- url: /.*
  script: _go_app
