application: myapp
version: alpha-001
runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: static/css/

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/images/.*\.(gif|png|jpg)$

- url: /.*
  script: _go_app
